name: http_interop_io
description: Interop-compatible wrapper over the standard dart:io HTTP server.
version: 0.4.0
repository: https://github.com/f3ath/dart-http-interop-io

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
    http_interop: ^0.7.0

dev_dependencies:
  lints: ^2.0.1
  cider: ^0.1.5
  test: ^1.21.1
  check_coverage: ^0.0.2
  stream_channel: ^2.1.0
  http_interop_http: ^0.5.0

cider:
  link_template:
    tag: 'https://github.com/f3ath/dart-http-interop-io/releases/tag/%tag%'
    diff: 'https://github.com/f3ath/dart-http-interop-io/compare/%from%...%to%'
